name: Deploy To Cloud
on:
  release: 
    types:
      - released

permissions:
  contents: read

jobs:
  deploy-frontend:
    name: 'Deploy Frontend'
    environment: 'production-azure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        
      - name: Deploy Frontend to Azure
        id: deployfrontend
        env:
          CI: ""
          REACT_APP_REDIRECT_URI: ${{ vars.REACT_APP_REDIRECT_URI }}
          REACT_APP_AUTH_URL: ${{ vars.REACT_APP_AUTH_URL }}
          REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
          REACT_APP_AUTH_URL_BACKUP: ${{ vars.REACT_APP_AUTH_URL_BACKUP }}
          REACT_APP_API_BASE_URL_BACKUP: ${{ vars.REACT_APP_API_BASE_URL_BACKUP }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_POND_0D634B603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/frontend" #
          api_location: ""
          output_location: "build" 